# Generated by Django 3.2.5 on 2021-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('notes_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=30)),
                ('subject', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='notes/image')),
            ],
        ),
    ]
