# Generated by Django 3.2.5 on 2021-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.FileField(default='', upload_to='notes/images'),
        ),
    ]
