# Generated by Django 3.2.5 on 2021-08-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notes_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbms',
            name='file',
            field=models.FileField(default='', upload_to='notes/images'),
        ),
    ]
