# Generated by Django 3.2.5 on 2022-04-29 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_dbms_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbms',
            name='teacher_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
