# Generated by Django 3.2.5 on 2022-05-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_dbms_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
