# Generated by Django 3.2.5 on 2022-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('notice_file', models.FileField(default='', upload_to='notes/notices')),
            ],
        ),
    ]
